-- Gerado por Oracle SQL Developer Data Modeler 4.0.2.840
--   em:        2014-05-17 18:02:59 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE CARDAPIOS
  (
    CD_CARDAPIO         NUMBER (8) NOT NULL ,
    DT_CRIACAO_CARDAPIO DATE NOT NULL
  ) ;
ALTER TABLE CARDAPIOS ADD CONSTRAINT CARDAPIOS_PK PRIMARY KEY ( CD_CARDAPIO ) ;

CREATE TABLE CLIENTES
  (
    CD_TELEFONE_CLIENTE    NUMBER (11) NOT NULL ,
    NM_CLIENTE             VARCHAR2 (60) NOT NULL ,
    NM_ENDERECO_CLIENTE    VARCHAR2 (60) NOT NULL ,
    DS_OBSERVACOES_CLIENTE VARCHAR2 (200) NOT NULL ,
    DT_NASCIMENTO_CLIENTE  DATE NOT NULL,
    NM_EMAIL_CLIENTE       VARCHAR2(90) NOT NULL
  ) ;
ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY ( CD_TELEFONE_CLIENTE ) ;

CREATE TABLE EMAILS
  (
    CD_EMAIL         NUMBER (8) NOT NULL ,
    NM_ASSUNTO_EMAIL VARCHAR2 (100) NOT NULL ,
    DS_CONTEUDO_EMAIL CLOB ,
    DT_ENVIO_EMAIL DATE NOT NULL
  ) ;
ALTER TABLE EMAILS ADD CONSTRAINT EMAILS_PK PRIMARY KEY ( CD_EMAIL ) ;

CREATE TABLE ENTREGADORES
  (
    CD_ENTREGADOR NUMBER (8) NOT NULL ,
    NM_ENTREGADOR VARCHAR2 (60 CHAR) NOT NULL
  ) ;
ALTER TABLE ENTREGADORES ADD CONSTRAINT ENTREGADORES_PK PRIMARY KEY ( CD_ENTREGADOR ) ;

CREATE TABLE ITENS_CARDAPIO
  (
    CD_CARDAPIO NUMBER (8) NOT NULL ,
    CD_PRODUTO  NUMBER (8) NOT NULL
  ) ;
ALTER TABLE ITENS_CARDAPIO ADD CONSTRAINT ITENS_CARDAPIO_PK PRIMARY KEY ( CD_CARDAPIO, CD_PRODUTO ) ;

CREATE TABLE ITENS_PEDIDO
  (
    CD_PRODUTO          NUMBER (8) NOT NULL ,
    CD_PEDIDO           NUMBER (8) NOT NULL ,
    QT_ITEM_PEDIDO      NUMBER (4) NOT NULL ,
    PRODUTOS_CD_PRODUTO NUMBER (8) NOT NULL
  ) ;
ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT ITENS_PEDIDO_PK PRIMARY KEY ( CD_PRODUTO, CD_PEDIDO ) ;

CREATE TABLE LISTA_EMAIL
  (
    CD_TELEFONE_CLIENTE NUMBER (11) NOT NULL ,
    CD_EMAIL            NUMBER (8) NOT NULL
  ) ;
ALTER TABLE LISTA_EMAIL ADD CONSTRAINT LISTA_EMAIL_PK PRIMARY KEY ( CD_TELEFONE_CLIENTE, CD_EMAIL ) ;

CREATE TABLE PEDIDOS
  (
    CD_PEDIDO                    NUMBER (8) NOT NULL ,
    CLIENTES_CD_TELEFONE_CLIENTE NUMBER (11) NOT NULL ,
    ENTREGADORES_CD_ENTREGADOR   NUMBER (8) NOT NULL ,
    NM_TIPO_PAGAMENTO            VARCHAR2 (60) NOT NULL ,
    DS_PEDIDO                    VARCHAR2 (60) ,
    VL_PEDIDO                    NUMBER NOT NULL ,
    DT_CRIACAO_PEDIDO            DATE NOT NULL ,
    DT_ENVIO_PEDIDO              DATE ,
    DT_FECHAMENTO_PEDIDO         DATE ,
    NM_ENTREGADOR                VARCHAR2 (60) ,
    DS_TIPO_PEDIDO               VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE PEDIDOS ADD CONSTRAINT PEDIDOS_PK PRIMARY KEY ( CD_PEDIDO ) ;

CREATE TABLE PRODUTOS
  (
    CD_PRODUTO      NUMBER (8) NOT NULL ,
    CD_TIPO_PRODUTO NUMBER (8) NOT NULL ,
    NM_PRODUTO      VARCHAR2 (60 CHAR) NOT NULL ,
    DS_PRODUTO      VARCHAR2 (150 CHAR) ,
    VL_PRODUTO      NUMBER NOT NULL
  ) ;
ALTER TABLE PRODUTOS ADD CONSTRAINT PRODUTOS_PK PRIMARY KEY ( CD_PRODUTO ) ;
ALTER TABLE PRODUTOS ADD CONSTRAINT PRODUTOS__UN UNIQUE ( CD_TIPO_PRODUTO , NM_PRODUTO ) ;

CREATE TABLE REDES_SOCIAIS
  (
    CD_REDE_SOCIAL      NUMBER (8) NOT NULL ,
    NM_REDE_SOCIAL      VARCHAR2 (60 CHAR) NOT NULL ,
    DS_LINK_REDE_SOCIAL VARCHAR2 (150 CHAR) NOT NULL
  ) ;
ALTER TABLE REDES_SOCIAIS ADD CONSTRAINT REDES_SOCIAIS_PK PRIMARY KEY ( CD_REDE_SOCIAL ) ;

CREATE TABLE TIPOS_PRODUTO
  (
    CD_TIPO_PRODUTO NUMBER (8) NOT NULL ,
    NM_TIPO_PRODUTO VARCHAR2 (60 CHAR) NOT NULL
  ) ;
ALTER TABLE TIPOS_PRODUTO ADD CONSTRAINT TIPOS_PRODUTO_PK PRIMARY KEY ( CD_TIPO_PRODUTO ) ;

CREATE TABLE USUARIOS
  (
    CD_USUARIO            INTEGER NOT NULL ,
    NM_USUARIO            VARCHAR2 (60) NOT NULL ,
    NM_LOGIN_USUARIO      VARCHAR2 (20) NOT NULL ,
    CD_SENHA_USUARIO      VARCHAR2 (20) NOT NULL ,
    NM_PRIVILEGIO_USUARIO VARCHAR2 (60) DEFAULT 'Usu�rio' NOT NULL ,
    NM_EMAIL_USUARIO      VARCHAR2 (60) NOT NULL
  ) ;
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( CD_USUARIO ) ;

ALTER TABLE ITENS_CARDAPIO ADD CONSTRAINT ITENS_CARDAPIO_CARDAPIOS_FK FOREIGN KEY ( CD_CARDAPIO ) REFERENCES CARDAPIOS ( CD_CARDAPIO ) ;

ALTER TABLE ITENS_CARDAPIO ADD CONSTRAINT ITENS_CARDAPIO_PRODUTOS_FK FOREIGN KEY ( CD_PRODUTO ) REFERENCES PRODUTOS ( CD_PRODUTO ) ;

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT ITENS_PEDIDO_PEDIDOS_FK FOREIGN KEY ( CD_PEDIDO ) REFERENCES PEDIDOS ( CD_PEDIDO ) ;

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT ITENS_PEDIDO_PRODUTOS_FK FOREIGN KEY ( PRODUTOS_CD_PRODUTO ) REFERENCES PRODUTOS ( CD_PRODUTO ) ;

ALTER TABLE LISTA_EMAIL ADD CONSTRAINT LISTA_EMAIL_CLIENTES_FK FOREIGN KEY ( CD_TELEFONE_CLIENTE ) REFERENCES CLIENTES ( CD_TELEFONE_CLIENTE ) ;

ALTER TABLE LISTA_EMAIL ADD CONSTRAINT LISTA_EMAIL_EMAILS_FK FOREIGN KEY ( CD_EMAIL ) REFERENCES EMAILS ( CD_EMAIL ) ;

ALTER TABLE PEDIDOS ADD CONSTRAINT PEDIDOS_CLIENTES_FK FOREIGN KEY ( CLIENTES_CD_TELEFONE_CLIENTE ) REFERENCES CLIENTES ( CD_TELEFONE_CLIENTE ) ;

ALTER TABLE PEDIDOS ADD CONSTRAINT PEDIDOS_ENTREGADORES_FK FOREIGN KEY ( ENTREGADORES_CD_ENTREGADOR ) REFERENCES ENTREGADORES ( CD_ENTREGADOR ) ;

ALTER TABLE PRODUTOS ADD CONSTRAINT PRODUTOS_TIPOS_PRODUTO_FK FOREIGN KEY ( CD_TIPO_PRODUTO ) REFERENCES TIPOS_PRODUTO ( CD_TIPO_PRODUTO ) ;

CREATE SEQUENCE CARDAPIOS_CD_CARDAPIO_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER CARDAPIOS_CD_CARDAPIO_TRG BEFORE
  INSERT ON CARDAPIOS FOR EACH ROW WHEN (NEW.CD_CARDAPIO IS NULL) BEGIN :NEW.CD_CARDAPIO := CARDAPIOS_CD_CARDAPIO_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE EMAILS_CD_EMAIL_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER EMAILS_CD_EMAIL_TRG BEFORE
  INSERT ON EMAILS FOR EACH ROW WHEN (NEW.CD_EMAIL IS NULL) BEGIN :NEW.CD_EMAIL := EMAILS_CD_EMAIL_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE ENTREGADORES_CD_ENTREGADOR_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER ENTREGADORES_CD_ENTREGADOR_TRG BEFORE
  INSERT ON ENTREGADORES FOR EACH ROW WHEN (NEW.CD_ENTREGADOR IS NULL) BEGIN :NEW.CD_ENTREGADOR := ENTREGADORES_CD_ENTREGADOR_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE ITENS_PEDIDO_CD_PRODUTO_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER ITENS_PEDIDO_CD_PRODUTO_TRG BEFORE
  INSERT ON ITENS_PEDIDO FOR EACH ROW WHEN (NEW.CD_PRODUTO IS NULL) BEGIN :NEW.CD_PRODUTO := ITENS_PEDIDO_CD_PRODUTO_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE PEDIDOS_CD_PEDIDO_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER PEDIDOS_CD_PEDIDO_TRG BEFORE
  INSERT ON PEDIDOS FOR EACH ROW WHEN (NEW.CD_PEDIDO IS NULL) BEGIN :NEW.CD_PEDIDO := PEDIDOS_CD_PEDIDO_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE PRODUTOS_CD_PRODUTO_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER PRODUTOS_CD_PRODUTO_TRG BEFORE
  INSERT ON PRODUTOS FOR EACH ROW WHEN (NEW.CD_PRODUTO IS NULL) BEGIN :NEW.CD_PRODUTO := PRODUTOS_CD_PRODUTO_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE REDES_SOCIAIS_CD_REDE_SOCIAL START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER REDES_SOCIAIS_CD_REDE_SOCIAL BEFORE
  INSERT ON REDES_SOCIAIS FOR EACH ROW WHEN (NEW.CD_REDE_SOCIAL IS NULL) BEGIN :NEW.CD_REDE_SOCIAL := REDES_SOCIAIS_CD_REDE_SOCIAL.NEXTVAL;
END;
/

CREATE SEQUENCE TIPOS_PRODUTO_CD_TIPO_PRODUTO START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TIPOS_PRODUTO_CD_TIPO_PRODUTO BEFORE
  INSERT ON TIPOS_PRODUTO FOR EACH ROW WHEN (NEW.CD_TIPO_PRODUTO IS NULL) BEGIN :NEW.CD_TIPO_PRODUTO := TIPOS_PRODUTO_CD_TIPO_PRODUTO.NEXTVAL;
END;
/

CREATE SEQUENCE USUARIOS_CD_USUARIO_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER USUARIOS_CD_USUARIO_TRG BEFORE
  INSERT ON USUARIOS FOR EACH ROW WHEN (NEW.CD_USUARIO IS NULL) BEGIN :NEW.CD_USUARIO := USUARIOS_CD_USUARIO_SEQ.NEXTVAL;
END;
/


-- Relat�rio do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           9
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          9
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
